/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Formulari extends javax.swing.JFrame {

    /**
     * Creates new form Formulari
     */
    public Formulari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aplikobtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mbiemrifield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emrifield = new javax.swing.JTextField();
        moshafield = new javax.swing.JTextField();
        komunafield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        pwfield = new javax.swing.JPasswordField();
        pwfield2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fshijbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nota10field = new javax.swing.JTextField();
        notamesfield = new javax.swing.JTextField();
        nota11field = new javax.swing.JTextField();
        nota12field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emrierror = new javax.swing.JLabel();
        mbiemrierror = new javax.swing.JLabel();
        moshaerror = new javax.swing.JLabel();
        komunaerror = new javax.swing.JLabel();
        emailerror = new javax.swing.JLabel();
        pwerror = new javax.swing.JLabel();
        pw2error = new javax.swing.JLabel();
        nota10error = new javax.swing.JLabel();
        nota11error = new javax.swing.JLabel();
        notameserror = new javax.swing.JLabel();
        nota12error = new javax.swing.JLabel();
        komuna2field = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        komuna2error = new javax.swing.JLabel();
        shkollafield = new javax.swing.JTextField();
        shkolla = new javax.swing.JLabel();
        shkollaerror = new javax.swing.JLabel();
        institucionifield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fakultetifield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        specializimifield = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lokacionifield = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        institucionierror = new javax.swing.JLabel();
        fakultetierror = new javax.swing.JLabel();
        specializimierror = new javax.swing.JLabel();
        lokacionierror = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sukses = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikimi për studime");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Emri:");

        aplikobtn.setBackground(new java.awt.Color(0, 204, 0));
        aplikobtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        aplikobtn.setText("Apliko");
        aplikobtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));
        aplikobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplikobtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Lt", 3, 30)); // NOI18N
        jLabel2.setText("Aplikimi për studime Bachelor");

        mbiemrifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mbiemrifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mbiemrifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbiemrifieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Mbiemri:");

        emrifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emrifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        moshafield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        moshafield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        komunafield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        komunafield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        komunafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komunafieldActionPerformed(evt);
            }
        });

        emailfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pwfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pwfield2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Mosha:");

        jLabel5.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Komuna:");

        jLabel6.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Passwordi:");

        jLabel9.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("Konfirmo passwordin:");

        jLabel8.setFont(new java.awt.Font("Roboto Lt", 3, 18)); // NOI18N
        jLabel8.setText("Të dhënat personale");

        fshijbtn.setBackground(new java.awt.Color(255, 0, 0));
        fshijbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        fshijbtn.setText("Fshij");
        fshijbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        fshijbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fshijbtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Lt", 3, 18)); // NOI18N
        jLabel10.setText("Të dhënat e shkollimit të mesëm");

        nota10field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nota10field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nota10field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota10fieldActionPerformed(evt);
            }
        });

        notamesfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notamesfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        notamesfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notamesfieldActionPerformed(evt);
            }
        });

        nota11field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nota11field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nota12field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nota12field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel11.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Nota Kl 10:");

        jLabel12.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Nota mesatare:");

        jLabel13.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("Nota Kl 11:");

        jLabel14.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Nota Kl 12:");

        emrierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        emrierror.setForeground(new java.awt.Color(255, 0, 0));

        mbiemrierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        mbiemrierror.setForeground(new java.awt.Color(255, 0, 0));

        moshaerror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        moshaerror.setForeground(new java.awt.Color(255, 0, 0));

        komunaerror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        komunaerror.setForeground(new java.awt.Color(255, 0, 0));

        emailerror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        emailerror.setForeground(new java.awt.Color(255, 0, 0));

        pwerror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        pwerror.setForeground(new java.awt.Color(255, 0, 0));

        pw2error.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        pw2error.setForeground(new java.awt.Color(255, 0, 0));

        nota10error.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        nota10error.setForeground(new java.awt.Color(255, 0, 0));

        nota11error.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        nota11error.setForeground(new java.awt.Color(255, 0, 0));

        notameserror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        notameserror.setForeground(new java.awt.Color(255, 0, 0));

        nota12error.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        nota12error.setForeground(new java.awt.Color(255, 0, 0));

        komuna2field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        komuna2field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        komuna2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komuna2fieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("Komuna:");

        komuna2error.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        komuna2error.setForeground(new java.awt.Color(255, 0, 0));

        shkollafield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        shkollafield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        shkollafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shkollafieldActionPerformed(evt);
            }
        });

        shkolla.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        shkolla.setForeground(new java.awt.Color(0, 51, 153));
        shkolla.setText("Shkolla e mesme:");

        shkollaerror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        shkollaerror.setForeground(new java.awt.Color(255, 0, 0));

        institucionifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        institucionifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel16.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setText("Institucioni:");

        fakultetifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fakultetifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fakultetifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakultetifieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("Fakulteti:");

        specializimifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        specializimifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        specializimifield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializimifieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("Specializimi:");

        lokacionifield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lokacionifield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel19.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 153));
        jLabel19.setText("Lokacioni:");

        institucionierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        institucionierror.setForeground(new java.awt.Color(255, 0, 0));

        fakultetierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        fakultetierror.setForeground(new java.awt.Color(255, 0, 0));

        specializimierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        specializimierror.setForeground(new java.awt.Color(255, 0, 0));

        lokacionierror.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        lokacionierror.setForeground(new java.awt.Color(255, 0, 0));

        jLabel24.setFont(new java.awt.Font("Roboto Lt", 3, 18)); // NOI18N
        jLabel24.setText("Të dhënat për aplikim");

        fail.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        fail.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pwerror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(komunaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emrierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mbiemrierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(moshaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emrifield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mbiemrifield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(komunafield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(moshafield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pwfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pw2error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(emailerror, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nota11field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(notamesfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nota10field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(komuna2field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nota12field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(shkollaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nota11error, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nota10error, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nota12error, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(komuna2error, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(shkolla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(shkollafield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fakultetierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(institucionifield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fakultetifield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(specializimifield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lokacionifield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(institucionierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(specializimierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(notameserror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lokacionierror, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(aplikobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fshijbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel24))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(emrifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emrierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(mbiemrifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mbiemrierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moshafield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addComponent(moshaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(komunafield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(komunaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nota10field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(institucionifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nota10error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(institucionierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fakultetifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(nota11field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nota11error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fakultetierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nota12field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(specializimifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nota12error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specializimierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notamesfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(lokacionifield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notameserror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lokacionierror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(komuna2field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(5, 5, 5)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(komuna2error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shkollafield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shkolla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shkollaerror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(emailerror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(pwerror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(pw2error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aplikobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fshijbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        sukses.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        sukses.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(sukses, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(sukses, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Aplikimi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void specializimifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializimifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializimifieldActionPerformed

    private void fakultetifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakultetifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakultetifieldActionPerformed

    private void shkollafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shkollafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shkollafieldActionPerformed

    private void komuna2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komuna2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komuna2fieldActionPerformed

    private void notamesfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notamesfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notamesfieldActionPerformed

    private void nota10fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota10fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota10fieldActionPerformed

    private void fshijbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fshijbtnActionPerformed
        emrifield.setText("");
        mbiemrifield.setText("");
        moshafield.setText("");
        komunafield.setText("");
        emailfield.setText("");
        pwfield.setText("");
        pwfield2.setText("");
        nota10field.setText("");
        nota11field.setText("");
        nota12field.setText("");
        notamesfield.setText("");
        komuna2field.setText("");
        shkollafield.setText("");
        institucionifield.setText("");
        fakultetifield.setText("");
        specializimifield.setText("");
        lokacionifield.setText("");
        emrierror.setText("");
        mbiemrierror.setText("");
        moshaerror.setText("");
        komunaerror.setText("");
        emailerror.setText("");
        pwerror.setText("");
        pw2error.setText("");
        nota10error.setText("");
        nota11error.setText("");
        nota12error.setText("");
        notameserror.setText("");
        komuna2error.setText("");
        shkollaerror.setText("");
        institucionierror.setText("");
        fakultetierror.setText("");
        specializimierror.setText("");
        lokacionierror.setText("");
        sukses.setText("");
        fail.setText("");
    }//GEN-LAST:event_fshijbtnActionPerformed

    private void komunafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komunafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komunafieldActionPerformed

    private void mbiemrifieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbiemrifieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbiemrifieldActionPerformed

    private void aplikobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplikobtnActionPerformed
        String emri = emrifield.getText();
        String mbiemri = mbiemrifield.getText();
        String mosha = moshafield.getText();
        int moshaint = 0;
        try {
            moshaint = Integer.parseInt(mosha);
        } catch (NumberFormatException e) {

        }
        String komuna = komunafield.getText();
        String email = emailfield.getText();
        String pw = pwfield.getText();
        String pw2 = pwfield2.getText();
        String nota10 = nota10field.getText();
        try {
            double nota10int = Double.parseDouble(nota10);
        } catch (NumberFormatException e) {

        }
        String nota11 = nota11field.getText();
        try {
            double nota11int = Double.parseDouble(nota11);
        } catch (NumberFormatException e) {

        }
        String nota12 = nota12field.getText();
        try {
            double nota12int = Double.parseDouble(nota12);
        } catch (NumberFormatException e) {

        }
        String notames = notamesfield.getText();
        try {
            double notamesint = Double.parseDouble(notames);
        } catch (NumberFormatException e) {

        }
        String komuna2 = komuna2field.getText();
        String shkolla = shkollafield.getText();
        String institucioni = institucionifield.getText();
        String fakulteti = fakultetifield.getText();
        String specializimi = specializimifield.getText();
        String lokacioni = lokacionifield.getText();
        if (emri.equals("")) {
            emrierror.setText("Emri duhet të plotësohet!");
            sukses.setText("");
        } else if (emri.length() < 3) {
            emrierror.setText("Emri duhet të ketë më shumë se 2 karaktere!");
            sukses.setText("");

        } else {
            emrierror.setText("");
        }
        if (mbiemri.equals("")) {
            mbiemrierror.setText("Mbiemri duhet të plotësohet!");
            sukses.setText("");
        } else if (mbiemri.length() < 3) {
            mbiemrierror.setText("Mbiemri duhet të ketë më shumë se 2 karaktere!");
            sukses.setText("");
        } else {
            mbiemrierror.setText("");
        }
        if (mosha.equals("")) {
            moshaerror.setText("Mosha duhet të plotësohet!");
            sukses.setText("");
        } else if (moshaint < 18) {
            moshaerror.setText("Mosha nuk duhet të jetë më e vogël se 18!");
            sukses.setText("");

        } else {
            moshaerror.setText("");
        }
        if (komuna.equals("")) {
            komunaerror.setText("Komuna duhet të plotësohet!");
            sukses.setText("");
        } else {
            komunaerror.setText("");
        }
        if (email.equals("")) {
            emailerror.setText("Emaili duhet të plotësohet!");
            sukses.setText("");
        } else if (!email.contains("@") && (!(email.endsWith(".com") || email.endsWith(".info")))) {
            emailerror.setText("Emaili duhet të përmbajë \"@\" dhe të perfundoj me \".com\" ose \".info\"");
            sukses.setText("");
        } else if (!email.contains("@")) {
            emailerror.setText("Emaili duhet të përmbajë \"@\"");
            sukses.setText("");
        } else if (!(email.endsWith(".com") || email.endsWith(".info"))) {
            emailerror.setText("Emaili duhe të përfundoj me \".com\" ose \".info\"!");
            sukses.setText("");
        } else {
            emailerror.setText("");
        }
        if (pw.equals("")) {
            pwerror.setText("Passwordi duhet të plotësohet!");
            sukses.setText("");
        } else if (pw.length() < 6) {
            pwerror.setText("Passwordi duhet të ketë të paktën 6 karaktere");
            sukses.setText("");
        } else if (!pw.equals(pw2)) {
            pwerror.setText("Passwordat duhet të jenë të njejtë");
            sukses.setText("");

        } else {
            pwerror.setText("");
        }
        if (pw2.equals("")) {
            pw2error.setText("Passwordi duhet të plotësohet!");
            sukses.setText("");
        } else if (pw2.length() < 6) {
            pw2error.setText("Passwordi duhet të ketë të paktën 6 karaktere");
            sukses.setText("");
        } else if (!pw2.equals(pw)) {
            pw2error.setText("Passwordat duhet të jenë të njejtë");
            sukses.setText("");
        } else {
            pw2error.setText("");
        }
        if (nota10.equals("")) {
            nota10error.setText("Nota 10 duhet të plotësohet!");
            sukses.setText("");
        } else {
            nota10error.setText("");
        }
        if (nota11.equals("")) {
            nota11error.setText("Nota 11 duhet të plotësohet!");
            sukses.setText("");
        } else {
            nota11error.setText("");
        }
        if (nota12.equals("")) {
            nota12error.setText("Nota 12 duhet të plotësohet!");
            sukses.setText("");
        } else {
            nota12error.setText("");
        }
        if (notames.equals("")) {
            notameserror.setText("Nota mesatare duhet të plotësohet!");
            sukses.setText("");
        } else {
            notameserror.setText("");
        }
        if (komuna2.equals("")) {
            komuna2error.setText("Komuna duhet të plotësohet!");
            sukses.setText("");
        } else {
            komuna2error.setText("");
        }
        if (shkolla.equals("")) {
            shkollaerror.setText("Shkolla duhet të plotësohet!");
            sukses.setText("");
        } else {
            shkollaerror.setText("");
        }
        if (institucioni.equals("")) {
            institucionierror.setText("Institucioni duhet të plotësohet!");
            sukses.setText("");
        } else {
            institucionierror.setText("");
        }
        if (fakulteti.equals("")) {
            fakultetierror.setText("Fakulteti duhet të plotësohet!");
            sukses.setText("");
        } else {
            fakultetierror.setText("");
        }
        if (specializimi.equals("")) {
            specializimierror.setText("Specializimi duhet të plotësohet!");
            sukses.setText("");
        } else {
            specializimierror.setText("");
        }
        if (lokacioni.equals("")) {
            lokacionierror.setText("Lokacioni duhet të plotësohet!");
            sukses.setText("");
        } else {
            lokacionierror.setText("");
        }

        String erroret = (emrierror.getText() + mbiemrierror.getText() + moshaerror.getText() + komunaerror.getText() + emailerror.getText()
                + pwerror.getText() + pw2error.getText() + nota10error.getText() + nota11error.getText() + nota12error.getText() + notameserror.getText()
                + komuna2error.getText() + shkollaerror.getText() + institucionierror.getText() + fakultetierror.getText() + specializimierror.getText() + lokacionierror.getText());
        switch (erroret) {
            case "":
                sukses.setText("Aplikimi është kryer me sukses");
                fail.setText("");
                break;
            default:
                fail.setText("Aplikimi nuk është kryer me sukses");


    }//GEN-LAST:event_aplikobtnActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplikobtn;
    private javax.swing.JLabel emailerror;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emrierror;
    private javax.swing.JTextField emrifield;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel fakultetierror;
    private javax.swing.JTextField fakultetifield;
    private javax.swing.JButton fshijbtn;
    private javax.swing.JLabel institucionierror;
    private javax.swing.JTextField institucionifield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel komuna2error;
    private javax.swing.JTextField komuna2field;
    private javax.swing.JLabel komunaerror;
    private javax.swing.JTextField komunafield;
    private javax.swing.JLabel lokacionierror;
    private javax.swing.JTextField lokacionifield;
    private javax.swing.JLabel mbiemrierror;
    private javax.swing.JTextField mbiemrifield;
    private javax.swing.JLabel moshaerror;
    private javax.swing.JTextField moshafield;
    private javax.swing.JLabel nota10error;
    private javax.swing.JTextField nota10field;
    private javax.swing.JLabel nota11error;
    private javax.swing.JTextField nota11field;
    private javax.swing.JLabel nota12error;
    private javax.swing.JTextField nota12field;
    private javax.swing.JLabel notameserror;
    private javax.swing.JTextField notamesfield;
    private javax.swing.JLabel pw2error;
    private javax.swing.JLabel pwerror;
    private javax.swing.JPasswordField pwfield;
    private javax.swing.JPasswordField pwfield2;
    private javax.swing.JLabel shkolla;
    private javax.swing.JLabel shkollaerror;
    private javax.swing.JTextField shkollafield;
    private javax.swing.JLabel specializimierror;
    private javax.swing.JTextField specializimifield;
    private javax.swing.JLabel sukses;
    // End of variables declaration//GEN-END:variables
}
